#!/bin/bash

# (CUPS 2.2.2 이상, cups-filters 1.13.0 이상 필요)
PKG1_VER=$(dpkg-query -W -f='${Version}\n' cups)
PKG2_VER=$(dpkg-query -W -f='${Version}\n' cups-filters)

# Compare debian package version
# lt : <	gt : >
# $? == 0 or 1
if [[ $(dpkg --compare-versions ${PKG1_VER} "gt" "2.2.2") -eq 1 ]] ;  then
	echo "You need install higher than CUPS 2.2.2 version."
fi

if [[ $(dpkg --compare-versions ${PKG2_VER} "gt" "1.3.0") -eq 1 ]] ;  then
	echo "You need install higher than cups-filters 1.13.0 version."
fi

if [[ -f "/etc/cups/cups-browsed.conf" ]] ; then
	echo "Update Settings for Driverless Printer..."
	cp /etc/cups/cups-browsed.conf{,.bak}
	sed -i -e '/CreateIPPPrinterQueues Driverless/,+1d' /etc/cups/cups-browsed.conf
	sed -i -e '/CreateIPPPrinterQueues All/,+1d' /etc/cups/cups-browsed.conf

	echo "CreateIPPPrinterQueues Driverless" | tee -a /etc/cups/cups-browsed.conf > /dev/null 2>&1
	echo "CreateIPPPrinterQueues All" | tee -a /etc/cups/cups-browsed.conf  > /dev/null 2>&1

	systemctl restart cups cups-browsed || true
fi
